# Generated by Django 4.2.6 on 2024-02-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_genre_genreimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='genre_images'),
        ),
        migrations.DeleteModel(
            name='GenreImage',
        ),
    ]
