# Generated by Django 4.2.6 on 2024-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name_alphabet',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
