# Generated by Django 4.2.6 on 2024-02-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0003_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
