# Generated by Django 4.2.6 on 2024-02-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='images',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')]),
        ),
    ]
