# Generated by Django 4.2.6 on 2024-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='ユーザー名', max_length=10, verbose_name='ユーザー名'),
            preserve_default=False,
        ),
    ]
