# Generated by Django 4.2.6 on 2024-02-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0008_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
