# Generated by Django 4.2.6 on 2024-02-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0013_alter_review_name_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='restaurant',
        ),
    ]
