# Generated by Django 4.2.6 on 2024-02-25 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0014_rename_name_review_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.TimeField(verbose_name='予約日時')),
                ('numbers_of_ppl', models.IntegerField(default=0, verbose_name='予約人数')),
                ('create_date', models.TimeField(auto_now_add=True, verbose_name='作成日時')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commondb.restaurant', verbose_name='店舗ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
