# Generated by Django 4.2.6 on 2024-02-25 05:47

import commondb.models.booking
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0015_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(validators=[commondb.models.booking.future_date_validator], verbose_name='予約日'),
        ),
    ]
