# Generated by Django 4.2.6 on 2024-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondb', '0020_alter_booking_restaurant_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('address', models.CharField(max_length=100, verbose_name='所在地')),
                ('established_date', models.DateField(verbose_name='設立日')),
                ('capital', models.CharField(max_length=100, verbose_name='資本金')),
                ('number_of_staff', models.CharField(max_length=100, verbose_name='従業員数')),
            ],
        ),
    ]
